// priority: -9999
// @ts-check
// Datapacker utility functions for exporting recipes and conversion groups

// Object to hold datapacker related functions and state
// This is done to help identify datapacker related code and prevent namespace pollution
const datapacker = {

    // Want some debug?
    debug: false,

    /**
     * Converts an ID to a safe format by replacing unsafe characters.
     * @param {string} id
     */
    createSafeID: function (id) {
        let safeID = id.replace(/[^a-z0-9_.-]/gi, "_");
        if (this.debug && (safeID !== id)) console.log(`ID contained unsafe characters, converted to safe ID: ${safeID}`);
        return safeID;
    },

    /** 
     * Function to datapack export the recipe
     * @param {string} id - The file name for the recipe, must be unique.
     * @param {string} type - The type of the recipe, used to determine the folder structure.
     * @param {{
     *   json: import("com.google.gson.JsonObject").$JsonObject
     * }} recipe - The recipe object containing the JSON data.
     */
    exportDatapackRecipe: function (id, type, recipe) {
        // Map of recipe types to their corresponding paths
        let typePathMap = new Map([
            ["casting:melting", "kubejs/data/casting/recipe/lorem_ipsum.json"],
        ]);

        // Determine the path based on the recipe type
        let recipePath = typePathMap.get(type);
        if (!recipePath) throw new Error(`Unsupported recipe type: ${type}`);

        let path = recipePath.replace("lorem_ipsum", id);
        if (JsonIO.read(path)) {
            if (this.debug) console.log(`Datapack recipe already exists ${id}, skipping export.`);
            return;
        }

        // Write the recipe JSON to the specified path
        JsonIO.write(path, recipe.json);
        if (this.debug) console.log(`Created Datapack recipe for ${id}`);
        this.exportedDataPacks.set(id, { type: type, recipe: recipe });
        return path;
    },

    /**
     * @param {string} name - The name of the conversion group.
     * @param {string} path - The file path to write the conversion group to.
     * @param {string} comment - A comment describing the conversion group.
     * @param {Array<{
     *   ingredients: Array<{
     *     type: string,
     *     amount?: number,
     *     count?: number,
     *     id?: string,
     *     tag?: string
     *   }>,
     *   output: {
     *     type: string,
     *     amount?: number,
     *     count?: number,
     *     id?: string,
     *     tag?: string
     *   },
     * }>} conversions
     */
    addConversionGroup: function (name, comment, path, conversions) {

        // Output conversion must be a JsonObject
        if (!(conversions.find(c => JsonUtils.of(c.output).isJsonObject()))) {
            throw new Error("Output conversion must be a JsonObject");
        }

        JsonIO.write(path, {
            "comment": "Generated by KubeJS",
            "groups": (function () {
                let obj = {};
                obj[name] = {
                    "comment": comment,
                    "conversions": conversions
                };
                return obj;
            })()
        });

        if (this.debug) console.log(`Created conversion group ${name} at ${path}`);
        return path;
    }
}